services:
  - type: web
    name: unisearch-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.10.13
    healthCheckPath: /health
    envVarGroups:
      - unisearch-shared
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unisearch-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: API_HOST
        value: 0.0.0.0
      - key: FRONTEND_URLS
        value: https://unisearch-gamma.vercel.app,http://localhost:5173,http://localhost:3000
      - key: SECRET_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: INFO

databases:
  - name: unisearch-db
    plan: free
    databaseName: unisearch
    user: unisearch_user

envVarGroups:
  - name: unisearch-shared
    envVars:
      - key: CORS_ORIGINS
        value: '["https://unisearch-gamma.vercel.app"]'
      - key: CACHE_EXPIRY_HOURS
        value: "24"
      - key: ENABLE_DATA_VALIDATION
        value: "true"
      - key: AUTO_UPDATE_RANKINGS
        value: "false"
