services:
  # Backend API Service
  - type: web
    name: unisearch-api
    env: python
    plan: free
    region: oregon
    buildCommand: cd backend && pip install -r ../requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unisearch-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: API_HOST
        value: 0.0.0.0
      - key: FRONTEND_URL
        fromService:
          type: web
          name: unisearch-frontend
          property: host
      - key: SECRET_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: INFO

  # Frontend Static Site
  - type: web
    name: unisearch-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database
databases:
  - name: unisearch-db
    plan: free
    databaseName: unisearch
    user: unisearch_user

# Environment Groups (for shared environment variables)
envVarGroups:
  - name: unisearch-shared
    envVars:
      - key: CORS_ORIGINS
        value: '["https://unisearch-frontend.onrender.com"]'
      - key: CACHE_EXPIRY_HOURS
        value: "24"
      - key: ENABLE_DATA_VALIDATION
        value: "true"
      - key: AUTO_UPDATE_RANKINGS
        value: "false"